from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import tempfile
import tomllib
import uuid
from contextlib import contextmanager
from pathlib import Path, PurePosixPath
from typing import Iterator

MARKER = "Generated by scripts/sync_agents.py; edit canonical .agents sources."
MANIFEST = ".agents/generated-manifest.json"
CONFIG = ".agents/loom.json"
MANAGED_ROOTS = (
    PurePosixPath(".codex/agents"),
    PurePosixPath(".claude/agents"),
    PurePosixPath(".claude/skills"),
)
SENSITIVE_SKILL_NAMES = {".env", "id_rsa", "id_dsa", "id_ed25519"}
SENSITIVE_SKILL_SUFFIXES = {".key", ".pem", ".p12", ".pfx"}
IGNORED_SKILL_NAMES = {".DS_Store", "Thumbs.db"}
IGNORED_SKILL_SUFFIXES = {".pyc", ".swp", ".swo", "~"}


class RoleSyncError(ValueError):
    """Raised when rolesync cannot safely validate or synchronize a project."""


def _read_json(path: Path, label: str) -> dict:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RoleSyncError(f"{label}: {exc}") from exc
    if not isinstance(value, dict):
        raise RoleSyncError(f"{label}: expected a JSON object")
    return value


def _validate_relpath(rel: str, *, managed: bool = False) -> PurePosixPath:
    if not isinstance(rel, str) or not rel or "\\" in rel:
        raise RoleSyncError(f"Unsafe path: {rel!r}")
    p = PurePosixPath(rel)
    if p.is_absolute() or any(part in {"", ".", ".."} for part in p.parts):
        raise RoleSyncError(f"Unsafe path: {rel}")
    if managed and not any(p == root or root in p.parents for root in MANAGED_ROOTS):
        raise RoleSyncError(f"Path is outside rolesync managed roots: {rel}")
    return p


def _reject_symlink_chain(root: Path, path: Path) -> None:
    root = root.resolve()
    try:
        rel = path.relative_to(root)
    except ValueError as exc:
        raise RoleSyncError(f"Path escapes project root: {path}") from exc
    cursor = root
    for part in rel.parts:
        cursor = cursor / part
        if cursor.exists() and cursor.is_symlink():
            raise RoleSyncError(f"Refusing to operate through symlink: {cursor}")


def _safe_managed_path(root: Path, rel: str) -> Path:
    p = _validate_relpath(rel, managed=True)
    target = root.joinpath(*p.parts)
    _reject_symlink_chain(root, target.parent)
    resolved_root = root.resolve()
    resolved_target = target.resolve(strict=False)
    if not resolved_target.is_relative_to(resolved_root):
        raise RoleSyncError(f"Managed path escapes project root: {rel}")
    managed_root = next(m for m in MANAGED_ROOTS if p == m or m in p.parents)
    expected = root.joinpath(*managed_root.parts).resolve(strict=False)
    if not resolved_target.is_relative_to(expected):
        raise RoleSyncError(f"Managed path escapes its owned root: {rel}")
    return target


def _safe_metadata_path(root: Path, rel: str) -> Path:
    p = _validate_relpath(rel)
    if not (p == PurePosixPath(".agents") or PurePosixPath(".agents") in p.parents):
        raise RoleSyncError(f"Metadata path must stay under .agents: {rel}")
    target = root.joinpath(*p.parts)
    _reject_symlink_chain(root, target.parent)
    if not target.resolve(strict=False).is_relative_to(root.resolve()):
        raise RoleSyncError(f"Metadata path escapes project root: {rel}")
    return target


def _platforms(root: Path) -> set[str]:
    path = root / CONFIG
    if not path.exists():
        return {"claude", "codex"}
    config = _read_json(path, CONFIG)
    if config.get("schema_version") != 1:
        raise RoleSyncError(f"{CONFIG}: unsupported schema_version")
    values = config.get("platforms", ["claude", "codex"])
    if not isinstance(values, list) or not values or any(v not in {"claude", "codex"} for v in values):
        raise RoleSyncError(f"{CONFIG}: platforms must be a non-empty list containing only claude/codex")
    return set(values)


def _validate_catalog(root: Path) -> tuple[dict, str]:
    agents = root / ".agents"
    if not agents.is_dir() or agents.is_symlink():
        raise RoleSyncError(".agents must be a normal directory")
    catalog = _read_json(agents / "catalog.json", ".agents/catalog.json")
    if catalog.get("schema_version") != 1:
        raise RoleSyncError(".agents/catalog.json: unsupported schema_version")
    roles = catalog.get("roles")
    if not isinstance(roles, list):
        raise RoleSyncError(".agents/catalog.json: roles must be a list")
    common_path = agents / "common.md"
    if not common_path.is_file() or common_path.is_symlink():
        raise RoleSyncError(".agents/common.md must be a normal file")
    common = common_path.read_text(encoding="utf-8").strip()
    seen_ids: set[str] = set()
    seen_names: set[str] = set()
    required = {"id", "name", "description", "source", "skill", "codex", "claude"}
    for i, role in enumerate(roles):
        where = f".agents/catalog.json: roles[{i}]"
        if not isinstance(role, dict):
            raise RoleSyncError(f"{where} must be an object")
        missing = required - role.keys()
        if missing:
            raise RoleSyncError(f"{where} missing required fields: {', '.join(sorted(missing))}")
        if "enabled" in role and not isinstance(role["enabled"], bool):
            raise RoleSyncError(f"{where}.enabled must be a boolean when present")
        role_id = role["id"]
        name = role["name"]
        if not isinstance(role_id, str) or not role_id:
            raise RoleSyncError(f"{where}.id must be a non-empty string")
        if role_id in seen_ids:
            raise RoleSyncError(f"{where}.id duplicates {role_id}")
        seen_ids.add(role_id)
        if not isinstance(name, str) or not re.fullmatch(r"[a-z][a-z0-9-]*", name):
            raise RoleSyncError(f"{where}.name must be lowercase-kebab-case")
        if name in seen_names:
            raise RoleSyncError(f"{where}.name duplicates {name}")
        seen_names.add(name)
        if not isinstance(role["description"], str) or not role["description"].strip():
            raise RoleSyncError(f"{where}.description must be a non-empty string")
        source_rel = role["source"]
        if not isinstance(source_rel, str):
            raise RoleSyncError(f"{where}.source must be a string")
        source = (root / source_rel).resolve()
        roles_root = (agents / "roles").resolve()
        if not source.is_relative_to(roles_root) or not source.is_file():
            raise RoleSyncError(f"Role source outside canonical directory: {source}")
        if (root / source_rel).is_symlink():
            raise RoleSyncError(f"{where}.source must not be a symlink")
        skill = role["skill"]
        if not isinstance(skill, str) or not re.fullmatch(r"[a-z][a-z0-9-]*", skill):
            raise RoleSyncError(f"{where}.skill must be lowercase-kebab-case")
        skill_file = agents / "skills" / skill / "SKILL.md"
        if not skill_file.is_file() or skill_file.is_symlink():
            raise RoleSyncError(f"Missing skill: {skill}")
        codex = role["codex"]
        claude = role["claude"]
        if not isinstance(codex, dict) or not all(isinstance(codex.get(k), str) and codex[k] for k in ("model", "model_reasoning_effort", "sandbox_mode")):
            raise RoleSyncError(f"{where}.codex requires non-empty model, model_reasoning_effort, and sandbox_mode strings")
        if not isinstance(claude, dict):
            raise RoleSyncError(f"{where}.claude must be an object")
        for key in ("model", "permissionMode"):
            if not isinstance(claude.get(key), str) or not claude[key]:
                raise RoleSyncError(f"{where}.claude.{key} must be a non-empty string")
        if not isinstance(claude.get("tools"), list) or any(not isinstance(x, str) or not x for x in claude["tools"]):
            raise RoleSyncError(f"{where}.claude.tools must be a list of non-empty strings")
        if not isinstance(claude.get("maxTurns"), int) or isinstance(claude["maxTurns"], bool) or claude["maxTurns"] <= 0:
            raise RoleSyncError(f"{where}.claude.maxTurns must be a positive integer")
        if claude.get("effort") is not None and not isinstance(claude["effort"], str):
            raise RoleSyncError(f"{where}.claude.effort must be a string or null")
        if claude.get("isolation") not in {None, "worktree"}:
            raise RoleSyncError(f"{where}.claude.isolation must be worktree or null")
    return catalog, common


def _skip_skill_path(path: Path) -> bool:
    if any(part == "__pycache__" for part in path.parts):
        return True
    if path.name in IGNORED_SKILL_NAMES:
        return True
    return any(path.name.endswith(suffix) for suffix in IGNORED_SKILL_SUFFIXES)


def _reject_sensitive_skill_path(path: Path) -> None:
    lower = path.name.lower()
    if lower in SENSITIVE_SKILL_NAMES or lower.startswith(".env.") or path.suffix.lower() in SENSITIVE_SKILL_SUFFIXES:
        raise RoleSyncError(f"Refusing to mirror likely secret from skill resources: {path.as_posix()}")


def _skill_files(root: Path) -> Iterator[tuple[Path, Path]]:
    skills = root / ".agents/skills"
    if not skills.is_dir() or skills.is_symlink():
        raise RoleSyncError(".agents/skills must be a normal directory")
    for current, dirs, files in os.walk(skills, followlinks=False):
        current_path = Path(current)
        for dirname in list(dirs):
            child = current_path / dirname
            if child.is_symlink():
                raise RoleSyncError(f"Canonical skills must not contain symlink directories: {child}")
            if dirname == "__pycache__":
                dirs.remove(dirname)
        for filename in files:
            source = current_path / filename
            rel = source.relative_to(skills)
            if source.is_symlink():
                raise RoleSyncError(f"Canonical skills must not contain symlink files: {source}")
            if _skip_skill_path(rel):
                continue
            _reject_sensitive_skill_path(rel)
            yield source, rel


def render(root: Path) -> dict[str, bytes]:
    root = root.resolve()
    catalog, common = _validate_catalog(root)
    platforms = _platforms(root)
    output: dict[str, bytes] = {}
    for role in catalog["roles"]:
        if role.get("enabled", True) is False:
            continue
        name = role["name"]
        body = (root / role["source"]).read_text(encoding="utf-8").strip()
        skill = role["skill"]
        instructions = common + "\n\n" + body + f"\n\nPrimary workflow: `.agents/skills/{skill}/SKILL.md`."
        if "codex" in platforms:
            cx = role["codex"]
            fields = {
                "name": name,
                "description": role["description"],
                "model": cx["model"],
                "model_reasoning_effort": cx["model_reasoning_effort"],
                "sandbox_mode": cx["sandbox_mode"],
            }
            toml = "# " + MARKER + "\n" + "\n".join(
                f"{k} = {json.dumps(v, ensure_ascii=False)}" for k, v in fields.items()
            ) + "\n"
            if "'''" not in instructions:
                toml += "developer_instructions = '''\n" + instructions + "\n'''\n"
            else:
                toml += "developer_instructions = " + json.dumps(instructions, ensure_ascii=False) + "\n"
            try:
                tomllib.loads(toml)
            except tomllib.TOMLDecodeError as exc:
                raise RoleSyncError(f"Generated TOML for role {name!r} is invalid: {exc}") from exc
            output[f".codex/agents/{name}.toml"] = toml.encode("utf-8")
        if "claude" in platforms:
            cl = role["claude"]
            front = {
                "name": name,
                "description": role["description"],
                "model": cl["model"],
                "tools": cl["tools"],
                "permissionMode": cl["permissionMode"],
                "maxTurns": cl["maxTurns"],
                "skills": [skill],
            }
            role_instructions = instructions
            if cl.get("effort") is not None:
                front["effort"] = cl["effort"]
            if cl.get("isolation"):
                front["isolation"] = cl["isolation"]
                role_instructions += (
                    "\n\nNative worktree note: isolation can start from the default branch rather than the assigned base. "
                    "Before edits verify the base. Only in a fresh, clean runtime-created worktree, create a unique "
                    "worker branch from the verified assigned base when needed. Never reset an existing or dirty "
                    "checkout; report an unresolved base mismatch. Resuming escalated work requires the preserved "
                    "patch/dependency commits, not just a fresh default-branch checkout."
                )
            yaml = "---\n" + "\n".join(f"{k}: {json.dumps(v, ensure_ascii=False)}" for k, v in front.items())
            text_value = yaml + "\n---\n\n<!-- " + MARKER + " -->\n\n" + role_instructions + "\n"
            output[f".claude/agents/{name}.md"] = text_value.encode("utf-8")
    if "claude" in platforms:
        for source, rel in _skill_files(root):
            output[(PurePosixPath(".claude/skills") / PurePosixPath(rel.as_posix())).as_posix()] = source.read_bytes()
    return output


def _validate_manifest(value: dict) -> dict[str, str]:
    if value.get("schema_version") != 1:
        raise RoleSyncError(f"{MANIFEST}: unsupported schema_version")
    files = value.get("files")
    if not isinstance(files, dict):
        raise RoleSyncError(f"{MANIFEST}: files must be an object")
    result: dict[str, str] = {}
    for rel, digest in files.items():
        _validate_relpath(rel, managed=True)
        if not isinstance(digest, str) or not re.fullmatch(r"[0-9a-f]{64}", digest):
            raise RoleSyncError(f"{MANIFEST}: invalid sha256 for {rel!r}")
        result[rel] = digest
    return result


def _load_previous(root: Path) -> dict[str, str]:
    path = root / MANIFEST
    if not path.exists():
        return {}
    _safe_metadata_path(root, MANIFEST)
    return _validate_manifest(_read_json(path, MANIFEST))


def _digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _normalize_text(data: bytes) -> bytes | None:
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        return None
    if "\0" in text:
        return None
    return text.replace("\r\n", "\n").replace("\r", "\n").encode("utf-8")


def _ownership_digest(rel: str, data: bytes) -> str:
    normalized = _normalize_text(data)
    return _digest(normalized if normalized is not None else data)


def _equivalent_output(rel: str, actual: bytes, expected: bytes) -> bool:
    if actual == expected:
        return True
    normalized_actual = _normalize_text(actual)
    normalized_expected = _normalize_text(expected)
    if normalized_actual is None or normalized_expected is None:
        return False
    return normalized_actual == normalized_expected


def _matches_ownership(rel: str, data: bytes, expected: str | None) -> bool:
    if expected is None:
        return False
    return _digest(data) == expected or _ownership_digest(rel, data) == expected


def _expected_manifest(output: dict[str, bytes]) -> tuple[dict, bytes]:
    expected = {"schema_version": 1, "files": {p: _ownership_digest(p, data) for p, data in sorted(output.items())}}
    return expected, (json.dumps(expected, indent=2) + "\n").encode("utf-8")


def _problems(root: Path, output: dict[str, bytes], previous: dict[str, str], manifest_bytes: bytes) -> list[str]:
    problems: list[str] = []
    for rel, data in output.items():
        path = _safe_managed_path(root, rel)
        if not path.is_file() or not _equivalent_output(rel, path.read_bytes(), data):
            problems.append(rel)
    stale = sorted(set(previous) - set(output))
    problems.extend("stale:" + rel for rel in stale)
    manifest_path = _safe_metadata_path(root, MANIFEST)
    if not manifest_path.is_file() or not _equivalent_output(MANIFEST, manifest_path.read_bytes(), manifest_bytes):
        problems.append(MANIFEST)
    return problems


@contextmanager
def _project_lock(root: Path) -> Iterator[None]:
    lock_name = hashlib.sha256(str(root.resolve()).encode("utf-8")).hexdigest()[:24]
    lock_path = Path(tempfile.gettempdir()) / f"rolesync-{lock_name}.lock"
    handle = lock_path.open("a+b")
    handle.seek(0, os.SEEK_END)
    if handle.tell() == 0:
        handle.write(b"\0")
        handle.flush()
    handle.seek(0)
    try:
        if os.name == "nt":
            import msvcrt
            handle.seek(0)
            try:
                msvcrt.locking(handle.fileno(), msvcrt.LK_NBLCK, 1)
            except OSError as exc:
                raise RoleSyncError("Another rolesync process is already modifying this project") from exc
        else:
            import fcntl
            try:
                fcntl.flock(handle.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
            except OSError as exc:
                raise RoleSyncError("Another rolesync process is already modifying this project") from exc
        yield
    finally:
        try:
            if os.name == "nt":
                import msvcrt
                handle.seek(0)
                msvcrt.locking(handle.fileno(), msvcrt.LK_UNLCK, 1)
            else:
                import fcntl
                fcntl.flock(handle.fileno(), fcntl.LOCK_UN)
        finally:
            handle.close()


def _transaction_dirs(root: Path) -> list[Path]:
    agents = root / ".agents"
    return sorted(p for p in agents.glob(".rolesync-txn-*") if p.is_dir())


def _safe_backup_path(txn: Path, name: object) -> Path:
    if not isinstance(name, str) or not name or "/" in name or "\\" in name or name in {".", ".."}:
        raise RoleSyncError(f"Invalid transaction backup reference: {name!r}")
    backups_dir = (txn / "backups").resolve()
    candidate = (txn / "backups" / name).resolve(strict=False)
    if not candidate.is_relative_to(backups_dir):
        raise RoleSyncError(f"Transaction backup escapes its directory: {name!r}")
    return candidate


def _restore_transaction(root: Path, txn: Path) -> None:
    journal_path = txn / "journal.json"
    if not journal_path.is_file():
        shutil.rmtree(txn, ignore_errors=True)
        return
    journal = _read_json(journal_path, str(journal_path))
    if journal.get("state") != "applying" or not isinstance(journal.get("operations"), list):
        shutil.rmtree(txn, ignore_errors=True)
        return
    for op in reversed(journal["operations"]):
        if not isinstance(op, dict):
            raise RoleSyncError(f"Invalid transaction operation entry: {op!r}")
        rel = op.get("rel")
        target = _safe_metadata_path(root, rel) if rel == MANIFEST else _safe_managed_path(root, rel)
        backup_name = op.get("backup")
        backup = _safe_backup_path(txn, backup_name) if backup_name else None
        if backup and backup.is_file():
            target.parent.mkdir(parents=True, exist_ok=True)
            temp = target.with_name(target.name + ".rolesync-restore")
            shutil.copy2(backup, temp)
            os.replace(temp, target)
        elif op.get("created") and target.exists():
            if target.is_file() or target.is_symlink():
                target.unlink()
    shutil.rmtree(txn, ignore_errors=True)


def _recover_incomplete(root: Path) -> None:
    for txn in _transaction_dirs(root):
        _restore_transaction(root, txn)


def _apply_transaction(root: Path, output: dict[str, bytes], stale: list[str], manifest_bytes: bytes) -> None:
    txn = root / ".agents" / f".rolesync-txn-{uuid.uuid4().hex}"
    stage_dir = txn / "stage"
    backup_dir = txn / "backups"
    stage_dir.mkdir(parents=True)
    backup_dir.mkdir(parents=True)
    operations: list[dict] = []
    changes: list[tuple[str, Path, bytes | None]] = []
    for rel, data in output.items():
        target = _safe_managed_path(root, rel)
        if target.is_file() and _equivalent_output(rel, target.read_bytes(), data):
            continue
        changes.append((rel, target, data))
    for rel in stale:
        target = _safe_managed_path(root, rel)
        if target.exists():
            changes.append((rel, target, None))
    manifest_target = _safe_metadata_path(root, MANIFEST)
    if not manifest_target.is_file() or not _equivalent_output(MANIFEST, manifest_target.read_bytes(), manifest_bytes):
        changes.append((MANIFEST, manifest_target, manifest_bytes))
    for index, (rel, target, data) in enumerate(changes):
        backup_name = None
        created = not target.exists()
        if target.exists():
            if not target.is_file():
                raise RoleSyncError(f"Refusing to replace non-file managed path: {rel}")
            backup_name = f"{index}.bak"
            shutil.copy2(target, backup_dir / backup_name)
        stage_name = None
        if data is not None:
            stage_name = f"{index}.new"
            (stage_dir / stage_name).write_bytes(data)
        operations.append({"rel": rel, "backup": backup_name, "created": created, "stage": stage_name})
    journal_path = txn / "journal.json"
    journal_path.write_text(json.dumps({"state": "applying", "operations": operations}, indent=2) + "\n", encoding="utf-8")
    try:
        for op in operations:
            rel = op["rel"]
            target = _safe_metadata_path(root, rel) if rel == MANIFEST else _safe_managed_path(root, rel)
            if op["stage"] is None:
                target.unlink(missing_ok=True)
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            _reject_symlink_chain(root, target.parent)
            os.replace(stage_dir / op["stage"], target)
        journal_path.write_text(json.dumps({"state": "complete", "operations": operations}, indent=2) + "\n", encoding="utf-8")
    except BaseException:
        _restore_transaction(root, txn)
        raise
    shutil.rmtree(txn, ignore_errors=True)


def sync(root: Path, check: bool = False) -> list[str]:
    root = root.resolve()
    if not root.is_dir():
        raise RoleSyncError(f"Project root does not exist: {root}")
    if not check:
        with _project_lock(root):
            _recover_incomplete(root)
            return _sync_locked(root)
    output = render(root)
    previous = _load_previous(root)
    _, manifest_bytes = _expected_manifest(output)
    problems = _problems(root, output, previous, manifest_bytes)
    if _transaction_dirs(root):
        problems.append("incomplete-transaction")
    return problems


def _sync_locked(root: Path) -> list[str]:
    output = render(root)
    previous = _load_previous(root)
    _, manifest_bytes = _expected_manifest(output)
    problems = _problems(root, output, previous, manifest_bytes)
    for rel, data in output.items():
        target = _safe_managed_path(root, rel)
        if target.exists():
            if not target.is_file():
                raise RoleSyncError(f"Refusing to replace non-file managed path: {rel}")
            current = target.read_bytes()
            if current != data and not _matches_ownership(rel, current, previous.get(rel)):
                raise RoleSyncError(f"Refusing to overwrite untracked/hand-edited native file: {rel}. Reconcile it into canonical sources first.")
    stale = sorted(set(previous) - set(output))
    for rel in stale:
        target = _safe_managed_path(root, rel)
        if target.is_file() and not _matches_ownership(rel, target.read_bytes(), previous[rel]):
            raise RoleSyncError(f"Refusing to remove edited stale output: {rel}")
    _apply_transaction(root, output, stale, manifest_bytes)
    return problems


def validate_project(root: Path) -> list[str]:
    root = root.resolve()
    issues: list[str] = []
    try:
        render(root)
        _load_previous(root)
    except (OSError, UnicodeError, RoleSyncError, KeyError, TypeError) as exc:
        issues.append(str(exc))
    if _transaction_dirs(root):
        issues.append("Incomplete rolesync transaction is present; run `rolesync sync` to recover it")
    return issues
